//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string cartId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> quantity { get; set; }
        public int deleter { get; set; }
    }
}
