//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthenticationEntities : DbContext
    {
        public AuthenticationEntities()
            : base("name=AuthenticationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories1> categories1 { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<CustomerMVC> CustomerMVCs { get; set; }
        public virtual DbSet<D3MVC> D3MVC { get; set; }
        public virtual DbSet<order1> order1 { get; set; }
        public virtual DbSet<OrderDa> OrderDas { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<RolLogin> RolLogins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
        public virtual DbSet<userReg> userRegs { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<orderProduct> orderProducts { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
    }
}
