//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userReg()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int userId { get; set; }
        public string Fname { get; set; }
        public string Email { get; set; }
        public decimal PhoneNumber { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> RolLogin { get; set; }
        public string cartId { get; set; }
    
        public virtual RolLogin RolLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
